"""Mapbox Search Box API client for interactive place search.

Two-step by design. `/suggest` returns candidates *without* coordinates and
`/retrieve` turns one candidate into a full place, because Mapbox bills a
search session rather than each keystroke. The session token that ties the two
calls together is generated by the client and passed straight through — this
module never creates one, so the client stays in control of what counts as a
session.
"""

from __future__ import annotations

import os
from typing import Any, Optional

import httpx

from backend.services import cache as search_cache

SUGGEST_URL = "https://api.mapbox.com/search/searchbox/v1/suggest"
RETRIEVE_URL = "https://api.mapbox.com/search/searchbox/v1/retrieve"

MAPBOX_TOKEN = os.environ.get("MAPBOX_ACCESS_TOKEN", "")

# Shown wherever results are displayed; required by the Mapbox terms.
ATTRIBUTION = "© Mapbox © OpenStreetMap"

# Kept short because this backs a typeahead: a keystroke that is going to fail
# should fail while the user is still typing, not eight seconds later. The next
# keystroke retries anyway.
REQUEST_TIMEOUT_S = 2.5

# Suggestions churn as the user types, so they are held only long enough to
# absorb repeated keystrokes. A retrieved place is stable POI data and is kept
# longer, well inside what the Mapbox terms allow for performance caching.
SUGGEST_TTL_S = 300
RETRIEVE_TTL_S = 3600

MAX_LIMIT = 10


class SearchUnavailable(Exception):
    """Mapbox could not be reached, or no token is configured."""


class RateLimited(Exception):
    """Mapbox returned 429. Carries the provider's Retry-After when given.

    Raised rather than returned as an empty result so the caller cannot confuse
    a throttled request with a genuine "nothing found" — the same distinction
    place_image_service draws.
    """

    def __init__(self, retry_after: Optional[int] = None) -> None:
        super().__init__("Mapbox search rate limit reached")
        self.retry_after = retry_after


def _round_proximity(proximity: Optional[str]) -> str:
    """Bucket a "lng,lat" pair so nearby callers share one cache entry."""
    if not proximity:
        return "-"
    try:
        lng, lat = (float(part) for part in proximity.split(",", 1))
    except (TypeError, ValueError):
        return "-"
    return f"{lng:.2f},{lat:.2f}"


def _first(values: Any) -> Optional[str]:
    if isinstance(values, list) and values:
        return str(values[0])
    return None


def _context_name(context: dict, key: str) -> Optional[str]:
    entry = context.get(key)
    if isinstance(entry, dict):
        name = entry.get("name")
        return str(name) if name else None
    return None


async def _get_json(url: str, params: dict) -> dict:
    if not MAPBOX_TOKEN:
        raise SearchUnavailable("MAPBOX_ACCESS_TOKEN is not configured")

    try:
        async with httpx.AsyncClient(timeout=REQUEST_TIMEOUT_S) as client:
            response = await client.get(url, params={**params, "access_token": MAPBOX_TOKEN})
    except httpx.HTTPError as exc:
        # Name the exception class: httpx's network errors (ReadTimeout,
        # ConnectError, ...) all stringify to '', so interpolating only the
        # message produces "failed: " and loses which failure it was.
        detail = f"{type(exc).__name__}: {exc}" if str(exc) else type(exc).__name__
        raise SearchUnavailable(f"Mapbox search request failed: {detail}") from exc

    if response.status_code == 429:
        retry_after = response.headers.get("retry-after")
        raise RateLimited(int(retry_after) if retry_after and retry_after.isdigit() else None)
    if response.status_code >= 400:
        raise SearchUnavailable(f"Mapbox search returned {response.status_code}")

    try:
        return response.json()
    except ValueError as exc:
        raise SearchUnavailable("Mapbox search returned a non-JSON body") from exc


def _to_suggestion(raw: dict) -> Optional[dict]:
    """Adapt one /suggest entry. Returns None when it carries no usable id."""
    mapbox_id = raw.get("mapbox_id")
    if not mapbox_id:
        return None
    distance = raw.get("distance")
    return {
        "external_id": str(mapbox_id),
        "name": str(raw.get("name") or ""),
        # 'poi' is one physical place; 'brand' fans out to several on retrieve.
        "feature_type": str(raw.get("feature_type") or ""),
        "place_formatted": raw.get("place_formatted"),
        "full_address": raw.get("full_address"),
        "category": _first(raw.get("poi_category")),
        "distance_m": int(distance) if isinstance(distance, (int, float)) else None,
        "source": "mapbox",
    }


def _to_location(feature: dict) -> Optional[dict]:
    """Adapt one /retrieve feature into the shared LocationItem shape.

    Returns None when the feature has no coordinates, which is the one thing a
    saveable place cannot do without.
    """
    props = feature.get("properties") or {}

    coordinates = props.get("coordinates") or {}
    latitude = coordinates.get("latitude")
    longitude = coordinates.get("longitude")
    if latitude is None or longitude is None:
        geometry = (feature.get("geometry") or {}).get("coordinates") or []
        if len(geometry) < 2:
            return None
        longitude, latitude = geometry[0], geometry[1]

    try:
        latitude = float(latitude)
        longitude = float(longitude)
    except (TypeError, ValueError):
        return None

    context = props.get("context") or {}
    feature_type = str(props.get("feature_type") or "")

    return {
        "name": str(props.get("name_preferred") or props.get("name") or ""),
        "latitude": latitude,
        "longitude": longitude,
        "full_address": str(props.get("full_address") or props.get("place_formatted") or ""),
        "category": _first(props.get("poi_category")) or (feature_type or None),
        # Mapbox returns neither of these; the existing photo backfill fills
        # photo_url later from the place name.
        "description": None,
        "photo_url": None,
        "is_exact": feature_type == "poi",
        # Retrieve carries no match score, so none is reported rather than invented.
        "confidence": None,
        "source": "mapbox",
        "external_id": str(props.get("mapbox_id") or "") or None,
        "city": _context_name(context, "place"),
        "region": _context_name(context, "region"),
        "country": _context_name(context, "country"),
    }


async def suggest(
    query: str,
    session_token: str,
    proximity: Optional[str] = None,
    limit: int = MAX_LIMIT,
    language: str = "en",
    country: Optional[str] = None,
    types: Optional[str] = None,
) -> list[dict]:
    """Return search candidates for `query`. None of them carry coordinates."""
    normalized = " ".join(query.split()).lower()
    limit = max(1, min(limit, MAX_LIMIT))

    cache_key = (
        f"search:suggest:{language}:{country or '-'}:{types or '-'}:{limit}:"
        f"{_round_proximity(proximity)}:{normalized}"
    )
    cached = search_cache.get(cache_key)
    if cached is not None:
        return cached

    params: dict[str, Any] = {
        "q": query.strip(),
        "session_token": session_token,
        "limit": limit,
        "language": language,
    }
    if proximity:
        params["proximity"] = proximity
    if country:
        params["country"] = country
    if types:
        params["types"] = types

    payload = await _get_json(SUGGEST_URL, params)
    suggestions = [
        adapted
        for adapted in (_to_suggestion(raw) for raw in payload.get("suggestions") or [])
        if adapted is not None
    ]

    search_cache.set(cache_key, suggestions, ttl=SUGGEST_TTL_S)
    return suggestions


async def retrieve(mapbox_id: str, session_token: str) -> list[dict]:
    """Resolve one suggestion into full places.

    A list rather than a single place: retrieving a `brand` suggestion returns
    every branch Mapbox knows about, so callers must be ready for more than one.
    """
    cache_key = f"search:retrieve:{mapbox_id}"
    cached = search_cache.get(cache_key)
    if cached is not None:
        return cached

    payload = await _get_json(
        f"{RETRIEVE_URL}/{mapbox_id}",
        {"session_token": session_token},
    )
    locations = [
        adapted
        for adapted in (_to_location(feature) for feature in payload.get("features") or [])
        if adapted is not None
    ]

    search_cache.set(cache_key, locations, ttl=RETRIEVE_TTL_S)
    return locations
