import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  searchResultRow: { minHeight: 62 },
  searchResultsScroll: { maxHeight: 186 },
  // Atlas landing page: a quieter, editorial hierarchy that keeps the list
  // dense enough to browse without turning it into a stack of blue controls.
  eyebrow: { color: '#12C170', fontSize: 10, fontWeight: '800', letterSpacing: 1.1, marginBottom: 3 },
  planningBar: { marginHorizontal: 16, marginBottom: 4, padding: 12, borderRadius: 16, backgroundColor: '#F1F7F6', flexDirection: 'row', alignItems: 'center', gap: 10 },
  planningBarDisabled: { opacity: 0.55 },
  planningIcon: { width: 36, height: 36, borderRadius: 12, backgroundColor: '#D7ECE8', alignItems: 'center', justifyContent: 'center' },
  planningCopy: { flex: 1, minWidth: 0 },
  planningTitle: { color: '#1A1A1A', fontSize: 13, fontWeight: '700' },
  planningSubtitle: { color: '#62817E', fontSize: 11, lineHeight: 15, marginTop: 2 },
  sectionLabel: { color: '#12C170', fontSize: 10, fontWeight: '800', letterSpacing: 1 },
  focusIntro: { flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-between', marginBottom: 10 },
  focusHeading: { color: '#1A1A1A', fontSize: 18, fontWeight: '700', marginTop: 3 },
  focusCount: { color: '#6B807E', fontSize: 12, fontWeight: '600', marginBottom: 2 },
  focusMeta: { color: '#71827F', fontSize: 11, marginTop: 3 },
  focusRowCopy: { flex: 1, minWidth: 0 },
  focusImageWrap: { width: 48, height: 48, borderRadius: 12, overflow: 'hidden', backgroundColor: '#DFEBE8' },
  focusImage: { width: '100%', height: '100%' },
  focusImageFallback: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  simpleStartRow: { minHeight: 68, padding: 9, borderRadius: 14, backgroundColor: '#F4F0FF', borderWidth: 1, borderColor: '#E1D7FF', flexDirection: 'row', alignItems: 'center', gap: 10 },
  simpleStartButton: { minHeight: 68, marginTop: 12, padding: 9, borderRadius: 14, backgroundColor: '#F4F0FF', borderWidth: 1, borderColor: '#E1D7FF', flexDirection: 'row', alignItems: 'center', gap: 10 },
  createLanding: { flex: 1, minHeight: 0, paddingHorizontal: 16, paddingTop: 18, paddingBottom: 10 },
  simpleStartHero: { flexGrow: 0, flexShrink: 0, minHeight: 190, justifyContent: 'center' },
  simpleStartHeroButton: { width: '88%', minHeight: 132, alignSelf: 'center', padding: 16, borderRadius: 24, backgroundColor: '#FFFFFF', borderWidth: StyleSheet.hairlineWidth, borderColor: '#DCE7E4', justifyContent: 'space-between', shadowColor: '#12C170', shadowOpacity: 0.08, shadowRadius: 12, shadowOffset: { width: 0, height: 5 }, elevation: 3 },
  simpleStartHeroTop: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between' },
  simpleStartHeroIcon: { width: 54, height: 54, borderRadius: 17, backgroundColor: '#E8F9EF', alignItems: 'center', justifyContent: 'center' },
  simpleStartHeroCopy: { minWidth: 0 },
  simpleStartHeroTitle: { color: '#1A1A1A', fontSize: 19, fontWeight: '800' },
  simpleStartHeroSubtitle: { color: '#6B807E', fontSize: 12, lineHeight: 17, marginTop: 4 },
  planListSection: { flex: 1, minHeight: 0, paddingTop: 4 },
  simpleStartIcon: { width: 48, height: 48, borderRadius: 12, backgroundColor: '#885CF6', alignItems: 'center', justifyContent: 'center', shadowColor: '#885CF6', shadowOpacity: 0.22, shadowRadius: 8, shadowOffset: { width: 0, height: 3 } },
  simpleStartTitle: { color: '#5137A1', fontSize: 14, fontWeight: '800' },
  headerRight: { flexShrink: 0, flexDirection: 'row', alignItems: 'center', gap: 8, maxWidth: '52%' },
  focusAreaButton: { flexShrink: 1, maxWidth: 150, minHeight: 36, paddingHorizontal: 8, borderRadius: 10, backgroundColor: '#F4F4F5', flexDirection: 'row', alignItems: 'center', gap: 7 },
  focusAreaButtonText: { color: '#303033', fontSize: 16, fontWeight: '500', flexShrink: 1 },
  emptyAtlas: { flex: 1, paddingHorizontal: 15, paddingTop: 14, paddingBottom: 14, backgroundColor: '#FFFFFF' },
  emptyAtlasIntro: { paddingHorizontal: 4, paddingBottom: 15, gap: 8 },
  emptyAtlasKicker: { width: 76, height: 8, borderRadius: 4, backgroundColor: '#D9E1E4' },
  emptyAtlasTitle: { width: '58%', height: 15, borderRadius: 7, backgroundColor: '#CBD5D9' },
  emptyAtlasGroup: { marginBottom: 8 },
  emptyAtlasActions: { minHeight: 28, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, marginBottom: 4 },
  emptyAtlasAction: { width: 74, height: 20, borderRadius: 10, backgroundColor: '#E2E8EB' },
  emptyAtlasActionShort: { width: 92 },
  emptyAtlasRow: { minHeight: 74, padding: 10, borderRadius: 14, backgroundColor: '#F4F6F7', flexDirection: 'row', alignItems: 'center', gap: 10 },
  emptyAtlasOrder: { width: 27, height: 27, borderRadius: 14, backgroundColor: '#D7DEE1' },
  emptyAtlasImage: { width: 52, height: 52, borderRadius: 12, backgroundColor: '#DCE3E6' },
  emptyAtlasCopy: { flex: 1, gap: 9 },
  typewriterLine: { flexDirection: 'row', minHeight: 18 },
  emptyAtlasHint: { color: '#64727A', fontSize: 13, lineHeight: 18, fontWeight: '700' },
  emptyAtlasHintSub: { color: '#98A4AA', fontSize: 10, lineHeight: 14, minHeight: 14 },
  emptyAtlasLine: { width: '78%', height: 11, borderRadius: 6, backgroundColor: '#D3DBDE' },
  emptyAtlasLineShort: { width: '48%', height: 9, backgroundColor: '#DEE4E7' },
  emptyAtlasHandle: { width: 25, height: 34, borderRadius: 8, backgroundColor: '#E0E6E8' },
  emptyAtlasConnector: { width: 2, height: 16, borderRadius: 1, alignSelf: 'center', backgroundColor: '#DDE4E7' },
  mapSearchLayer: { position: 'absolute', top: 62, left: 16, right: 16, zIndex: 20 },
  mapSearchBox: { minHeight: 46, borderRadius: 18, backgroundColor: '#FFFFFF', flexDirection: 'row', alignItems: 'center', paddingHorizontal: 13, gap: 8, shadowColor: '#111827', shadowOpacity: 0.14, shadowRadius: 16, shadowOffset: { width: 0, height: 6 }, elevation: 7 },
  localMustSeesNoteRow: { alignSelf: 'flex-start' },
  localMustSeesNote: { alignSelf: 'flex-start', maxWidth: '100%', minHeight: 30, marginTop: 7, paddingLeft: 9, paddingRight: 5, borderRadius: 12, backgroundColor: 'rgba(255,255,255,0.94)', flexDirection: 'row', alignItems: 'center', gap: 6, shadowColor: '#111827', shadowOpacity: 0.08, shadowRadius: 8, shadowOffset: { width: 0, height: 3 }, elevation: 3 },
  localMustSeesDot: { width: 7, height: 7, borderRadius: 4, backgroundColor: '#8B5CF6' },
  localMustSeesText: { color: '#555162', fontSize: 10, fontWeight: '700', flexShrink: 1 },
  localMustSeesClose: { width: 24, height: 26, alignItems: 'center', justifyContent: 'center' },
  nearbyPromptRow: { alignSelf: 'flex-start' },
  nearbyPrompt: { alignSelf: 'flex-start', minHeight: 32, marginTop: 5, paddingHorizontal: 10, borderRadius: 13, backgroundColor: '#F4F0FF', borderWidth: StyleSheet.hairlineWidth, borderColor: '#DED3FF', flexDirection: 'row', alignItems: 'center', shadowColor: '#4C347E', shadowOpacity: 0.1, shadowRadius: 7, shadowOffset: { width: 0, height: 3 }, elevation: 3 },
  nearbyPromptMain: { minHeight: 30, flexDirection: 'row', alignItems: 'center', gap: 6 },
  nearbyPromptText: { color: '#6043AD', fontSize: 10, fontWeight: '800' },
  searchClose: { width: 28, height: 28, borderRadius: 14, backgroundColor: '#F1F5F9', alignItems: 'center', justifyContent: 'center' },
  searchSubmit: { width: 30, height: 30, borderRadius: 15, backgroundColor: '#EFF6FF', alignItems: 'center', justifyContent: 'center' },
  addResultButtonPending: { backgroundColor: '#94A3B8' },
  focusResultButton: { width: 30, height: 30, borderRadius: 15, alignItems: 'center', justifyContent: 'center', backgroundColor: '#12C170' },
  candidateSlot: { minHeight: 94, paddingTop: 8, paddingBottom: 14, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: '#DDE7E5', backgroundColor: '#FFFFFF', alignItems: 'center', justifyContent: 'flex-end' },
  candidateDescription: { width: 280, minHeight: 15, color: '#638078', fontSize: 11, lineHeight: 15, marginBottom: 6 },
  candidateActions: { width: 280, height: 46, position: 'relative', alignSelf: 'center' },
  candidateActionClip: { height: 46, overflow: 'hidden', position: 'absolute', top: 0 },
  candidateAddClip: { left: 0 },
  candidateSaveClip: { right: 216 },
  candidateAskClip: { right: 50 },
  candidateAdd: { width: 230, height: 46, borderRadius: 23, paddingLeft: 17, paddingRight: 8, backgroundColor: '#12C170', alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 8, shadowColor: '#0B8F52', shadowOpacity: 0.18, shadowRadius: 5, shadowOffset: { width: 0, height: 2 }, elevation: 2 },
  candidateAddDisabled: { backgroundColor: '#73CFA3' },
  candidateAddText: { flex: 1, minWidth: 0, color: '#FFFFFF', fontSize: 14, fontWeight: '800', textAlign: 'center' },
  candidateAddEmpty: { backgroundColor: '#EEF1F0', shadowOpacity: 0, elevation: 0 },
  candidateAddEmptyText: { flex: 1, minWidth: 0, color: '#7C8883', fontSize: 13, fontWeight: '700', textAlign: 'center' },
  candidateSave: { width: 64, height: 46, borderRadius: 23, backgroundColor: '#E8F5F0', borderWidth: StyleSheet.hairlineWidth, borderColor: '#BDE4D2', alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 3 },
  candidateSaveText: { color: '#155E46', fontSize: 11, fontWeight: '800' },
  candidateAsk: { width: 158, height: 46, borderRadius: 23, backgroundColor: '#12C170', alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 4 },
  candidateAskText: { color: '#FFFFFF', fontSize: 12, fontWeight: '800' },
  candidateFinish: { width: 42, height: 42, borderRadius: 21, position: 'absolute', right: 0, top: 2, backgroundColor: '#12C170', alignItems: 'center', justifyContent: 'center', shadowColor: '#12C170', shadowOpacity: 0.2, shadowRadius: 6, shadowOffset: { width: 0, height: 2 }, elevation: 2 },
  candidateFinishHit: { width: 42, height: 42, alignItems: 'center', justifyContent: 'center' },
  candidateFinishIcon: { position: 'absolute', alignItems: 'center', justifyContent: 'center' },
  candidateEmptyTitle: { width: 280, color: '#697A76', fontSize: 11, lineHeight: 15, fontWeight: '600', marginBottom: 6 },
  itemNoteModern: { color: '#475569', fontSize: 12, lineHeight: 17, marginTop: 5, paddingLeft: 8, borderLeftWidth: 2, borderLeftColor: '#CBD5E1', fontWeight: '500' },
  noteActions: { flexDirection: 'row', alignItems: 'center', gap: 3, flexShrink: 0 },
  noteVoiceButton: { width: 32, height: 32, borderRadius: 16, backgroundColor: '#F4F7F6', borderWidth: StyleSheet.hairlineWidth, borderColor: '#DCE7E3', alignItems: 'center', justifyContent: 'center' },
  fullSearch: { flex: 1, backgroundColor: '#FFFFFF', paddingTop: 54 },
  fullSearchHeader: { minHeight: 56, paddingHorizontal: 16, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: '#E5E7EB' },
  fullSearchTitle: { color: '#1A1A1A', fontSize: 17, fontWeight: '700' },
  fullResults: { padding: 16, gap: 8 },
  fullResultRow: { minHeight: 62, paddingHorizontal: 13, paddingVertical: 9, borderRadius: 14, backgroundColor: '#F8FAFC', flexDirection: 'row', alignItems: 'center', gap: 8 },
  dividerAddText: { color: '#64748B', fontSize: 10, fontWeight: '700' },
  dividerAddTextSelected: { color: '#12C170' },
  itemActionsRow: { minHeight: 34, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8 },
  transportInsertButton: { minHeight: 26, paddingHorizontal: 9, borderRadius: 13, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 4, backgroundColor: '#F1F5F9' },
  transportInsertButtonSelected: { backgroundColor: '#E6F5EC', borderWidth: StyleSheet.hairlineWidth, borderColor: '#B7E4CE' },
  timeTagInline: { borderRadius: 12, backgroundColor: '#EAF4FF', paddingHorizontal: 9, paddingVertical: 5 },
  modalRemoveButton: { alignSelf: 'center', marginTop: 6, marginBottom: 2, minHeight: 34, paddingHorizontal: 14, justifyContent: 'center' },
  modalRemoveText: { color: '#C24141', fontSize: 13, fontWeight: '700' },
  transportOptions: { paddingHorizontal: 18, paddingBottom: 28, gap: 8 },
  transportOption: { minHeight: 48, borderRadius: 12, paddingHorizontal: 14, flexDirection: 'row', alignItems: 'center', gap: 12, backgroundColor: '#F8FAFC' },
  transportOptionSelected: { backgroundColor: '#E6F5F1' },
  transportOptionText: { color: '#475569', fontSize: 15, fontWeight: '600' },
  transportOptionTextSelected: { color: '#12C170' },
  root: { flex: 1, backgroundColor: '#FFFFFF' }, header: { paddingHorizontal: 18, paddingTop: 18, paddingBottom: 14, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: '#E4ECEA' }, headerCopy: { flex: 1, minWidth: 0, paddingRight: 12 }, heading: { fontSize: 24, fontWeight: '700', color: '#1A1A1A' }, landingLabel: { color: '#12C170', fontSize: 12, fontWeight: '800', marginTop: 4 }, subheading: { fontSize: 12, color: '#74747B', marginTop: 2 }, headerIcon: { width: 36, height: 36, borderRadius: 12, backgroundColor: '#F0F4F3', alignItems: 'center', justifyContent: 'center' }, searchLayer: { paddingHorizontal: 16, zIndex: 4 }, searchBox: { minHeight: 46, borderRadius: 14, backgroundColor: '#F4F5F6', flexDirection: 'row', alignItems: 'center', paddingHorizontal: 13, gap: 8 }, searchInput: { flex: 1, fontSize: 16, color: '#1A1A1A', paddingVertical: 9 }, results: { marginTop: 6, backgroundColor: '#FFF', borderRadius: 14, overflow: 'hidden', shadowColor: '#000', shadowOpacity: 0.13, shadowRadius: 14, shadowOffset: { width: 0, height: 5 }, elevation: 5 }, resultRow: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 13, paddingVertical: 10, gap: 8, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: '#E7E8EA' }, resultCopy: { flex: 1 }, resultTitleRow: { flexDirection: 'row', alignItems: 'center', gap: 6 }, resultName: { color: '#1A1A1A', fontSize: 14, fontWeight: '600', flexShrink: 1 }, resultAddress: { color: '#77777D', fontSize: 12, marginTop: 2 }, savedTag: { backgroundColor: '#E9F3FF', borderRadius: 8, paddingHorizontal: 6, paddingVertical: 2 }, savedTagText: { color: '#2F78B4', fontSize: 10, fontWeight: '700' }, addResultButton: { width: 30, height: 30, borderRadius: 15, alignItems: 'center', justifyContent: 'center', backgroundColor: '#007AFF' }, pinPopup: { marginHorizontal: 16, marginTop: 10, borderRadius: 14, backgroundColor: '#FFFFFF', padding: 12, flexDirection: 'row', alignItems: 'center', shadowColor: '#000', shadowOpacity: 0.13, shadowRadius: 14, shadowOffset: { width: 0, height: 5 }, elevation: 5 }, pinName: { color: '#1A1A1A', fontSize: 14, fontWeight: '700' }, pinAddress: { color: '#77777D', fontSize: 12, marginTop: 2 }, pinAction: { width: 34, height: 34, borderRadius: 17, backgroundColor: '#007AFF', alignItems: 'center', justifyContent: 'center', marginLeft: 8 }, addedPill: { flexDirection: 'row', gap: 3, alignItems: 'center', backgroundColor: '#FFF0E6', borderRadius: 13, paddingHorizontal: 9, paddingVertical: 6 }, addedPillText: { color: '#B5551B', fontSize: 11, fontWeight: '700' }, listHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 18, paddingTop: 14, paddingBottom: 7 }, listHeading: { color: '#1A1A1A', fontSize: 18, fontWeight: '700' }, routeButton: { flexDirection: 'row', alignItems: 'center', gap: 4, minHeight: 34, paddingHorizontal: 10, borderWidth: 1, borderColor: '#B7D8D2', borderRadius: 10, backgroundColor: '#FFFFFF' }, routeButtonActive: { backgroundColor: '#12C170', borderColor: '#12C170' }, routeButtonText: { color: '#12C170', fontSize: 12, fontWeight: '700' }, routeButtonTextActive: { color: '#FFF' }, timeTags: { paddingHorizontal: 16, paddingBottom: 5, gap: 6 }, routeTimeTag: { borderRadius: 12, backgroundColor: '#F2F5F7', paddingHorizontal: 9, paddingVertical: 5 }, routeTimeTagText: { color: '#53616B', fontSize: 11, fontWeight: '600' }, emptyList: { flex: 1, paddingHorizontal: 18, paddingTop: 12, paddingBottom: 14 }, emptyText: { color: '#71827F', fontSize: 14, lineHeight: 20, maxWidth: 260 }, focusSection: { marginTop: 18, flexDirection: 'row', gap: 10, height: 122 }, focusList: { flex: 1 }, focusListContent: { gap: 10, paddingBottom: 16 }, focusRow: { minHeight: 70, padding: 10, borderRadius: 14, backgroundColor: '#F6F8F7', flexDirection: 'row', alignItems: 'center', gap: 10 }, focusText: { color: '#1A1A1A', fontSize: 14, fontWeight: '700', flexShrink: 1 }, focusRail: { width: 23, borderRadius: 12, backgroundColor: '#EFF1F2', alignItems: 'center', justifyContent: 'space-around', paddingVertical: 6 }, focusRailPaused: { backgroundColor: '#E0EDF7' }, focusRailThumb: { width: 4, height: 30, borderRadius: 2, backgroundColor: '#94B1C5' }, list: { flex: 1, paddingHorizontal: 15 }, listContent: { paddingBottom: 10 }, timeTag: { alignSelf: 'flex-start', borderRadius: 10, backgroundColor: '#EAF4FF', paddingHorizontal: 9, paddingVertical: 4, marginBottom: 5 }, timeTagText: { color: '#3179B7', fontSize: 11, fontWeight: '700' }, dividerAdd: { height: 19, alignItems: 'center', justifyContent: 'center' }, swipeShell: { marginBottom: 1, overflow: 'hidden', borderRadius: 14 }, deleteReveal: { width: 63, alignItems: 'center', justifyContent: 'center' }, deleteRevealHit: { width: 63, height: '100%', backgroundColor: '#E05252', alignItems: 'center', justifyContent: 'center' }, item: { minHeight: 70, padding: 9, borderRadius: 14, backgroundColor: '#FAFAFB', flexDirection: 'row', alignItems: 'center', gap: 9 }, orderBadge: { width: 28, height: 28, borderRadius: 14, backgroundColor: '#F5822A', alignItems: 'center', justifyContent: 'center' }, orderBadgeText: { color: '#FFFFFF', fontSize: 13, fontWeight: '800' }, itemImage: { width: 50, height: 50, borderRadius: 11, backgroundColor: '#E9EEF2' }, imageFallback: { alignItems: 'center', justifyContent: 'center' }, imageInitial: { color: '#426177', fontSize: 19, fontWeight: '700' }, itemCopy: { flex: 1, minWidth: 0 }, itemName: { fontSize: 14, fontWeight: '700', color: '#1A1A1A' }, itemAddress: { fontSize: 12, color: '#85858C', marginTop: 2 }, itemNote: { color: '#48708C', fontSize: 11, lineHeight: 15, marginTop: 4, fontStyle: 'italic' }, noteButton: { width: 40, height: 30, borderRadius: 9, backgroundColor: '#EEF6FD' }, dragHandle: { width: 28, height: 36, alignItems: 'center', justifyContent: 'center' }, footer: { flexDirection: 'row', paddingHorizontal: 16, paddingTop: 12, paddingBottom: 14, gap: 10, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: '#DDE7E5', backgroundColor: '#FFFFFF' }, secondarySaveText: { color: '#1A1A1A', fontSize: 14, fontWeight: '700' }, primarySaveText: { color: '#FFF', fontSize: 14, fontWeight: '700' }, modalBackdrop: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(0,0,0,0.28)' }, modalSheet: { borderTopLeftRadius: 22, borderTopRightRadius: 22, backgroundColor: '#FFF', paddingBottom: 28 }, modalHeader: { minHeight: 64, paddingHorizontal: 18, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: '#E5E5E8' }, modalCancel: { color: '#6D6D73', fontSize: 16 }, modalTitle: { color: '#1A1A1A', fontSize: 16, fontWeight: '700', textAlign: 'center' }, modalSubtitle: { color: '#85858C', fontSize: 11, textAlign: 'center', marginTop: 2 }, modalSave: { color: '#007AFF', fontSize: 16, fontWeight: '700' }, wheels: { height: 236, flexDirection: 'row', paddingHorizontal: 30 }, wheelContent: { paddingVertical: 72, flexGrow: 1 }, wheelDivider: { width: StyleSheet.hairlineWidth, backgroundColor: '#E8E8EC', marginVertical: 25 }, wheelOption: { minHeight: 40, justifyContent: 'center', alignItems: 'center', borderRadius: 10 }, wheelOptionSelected: { backgroundColor: '#EAF4FF' }, wheelOptionLocked: { opacity: 0.32 }, wheelText: { color: '#6A6A70', fontSize: 16 }, wheelTextSelected: { color: '#1874B8', fontWeight: '700' }, wheelTextLocked: { color: '#9CA3AF' }, noDayNote: { color: '#6B7280', fontSize: 12, lineHeight: 17, marginHorizontal: 30, marginTop: -12, textAlign: 'center' },
  editGuide: { color: '#667085', fontSize: 10, lineHeight: 14, fontWeight: '600', marginTop: 3 },
  atlasHeadingSafe: { lineHeight: 32, paddingTop: 2, includeFontPadding: true },
  timeConflictToast: { position: 'absolute', top: 70, left: 18, right: 18, minHeight: 38, paddingHorizontal: 12, paddingVertical: 9, borderRadius: 12, backgroundColor: '#FFF7E8', borderWidth: 1, borderColor: '#F3D29B', flexDirection: 'row', alignItems: 'center', gap: 7, zIndex: 10, shadowColor: '#9A6B2F', shadowOpacity: 0.12, shadowRadius: 8, shadowOffset: { width: 0, height: 3 }, elevation: 3 }, timeConflictText: { flex: 1, color: '#8A5600', fontSize: 12, lineHeight: 16, fontWeight: '600' },
});
