import Ionicons from '@expo/vector-icons/Ionicons';
import { Modal, Pressable, ScrollView, TouchableOpacity, View } from 'react-native';
import { Text } from '@/components/ui/text';
import { PLANNING_HOURS } from './constants';
import { styles } from './styles';

export function TimePickerModal({ visible, day, time, dayLocked, hasExisting, validationMessage, onChangeDay, onChangeTime, onClose, onRemove, onSave }: { visible: boolean; day: number | null; time: string; dayLocked: boolean; hasExisting: boolean; validationMessage?: string | null; onChangeDay: (day: number | null) => void; onChangeTime: (time: string) => void; onClose: () => void; onRemove: () => void; onSave: () => void }) {
  const dayOptions: Array<number | null> = [null, ...Array.from({ length: 14 }, (_, index) => index + 1)];
  return <Modal transparent animationType="slide" visible={visible} onRequestClose={onClose}><Pressable onPress={onClose} style={styles.modalBackdrop}><Pressable onPress={(event) => event.stopPropagation()} style={styles.modalSheet}><View style={styles.modalHeader}><TouchableOpacity onPress={onClose}><Text style={styles.modalCancel}>Cancel</Text></TouchableOpacity><View><Text style={styles.modalTitle}>Schedule time</Text><Text style={styles.modalSubtitle}>Place it in your itinerary</Text></View><TouchableOpacity onPress={onSave}><Text style={styles.modalSave}>Done</Text></TouchableOpacity></View>{validationMessage ? <View pointerEvents="none" style={styles.timeConflictToast}><Ionicons name="alert-circle-outline" size={16} color="#A15C00" /><Text numberOfLines={2} style={styles.timeConflictText}>{validationMessage}</Text></View> : null}<View style={styles.wheels}><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.wheelContent}>{dayOptions.map((value) => <TouchableOpacity disabled={dayLocked && value !== null} key={value ?? 'flexible-day'} onPress={() => onChangeDay(value)} style={[styles.wheelOption, day === value && styles.wheelOptionSelected, dayLocked && value !== null && styles.wheelOptionLocked]}><Text style={[styles.wheelText, day === value && styles.wheelTextSelected, dayLocked && value !== null && styles.wheelTextLocked]}>{value === null ? 'Flexible day' : `Day ${value}`}</Text></TouchableOpacity>)}</ScrollView><View style={styles.wheelDivider} /><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.wheelContent}>{PLANNING_HOURS.map((value) => <TouchableOpacity key={value} onPress={() => onChangeTime(value)} style={[styles.wheelOption, time === value && styles.wheelOptionSelected]}><Text style={[styles.wheelText, time === value && styles.wheelTextSelected]}>{value}</Text></TouchableOpacity>)}</ScrollView></View>{dayLocked ? <Text style={styles.noDayNote}>To assign a day, change a Flexible day time tag to a numbered day.</Text> : null}{hasExisting ? <TouchableOpacity onPress={onRemove} style={styles.modalRemoveButton}><Text style={styles.modalRemoveText}>Remove time</Text></TouchableOpacity> : null}</Pressable></Pressable></Modal>;
}
